/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cusc.helps;

import com.cusc.entities.CarRegistrationDetails;
import com.cusc.entities.TourRegistration;
import java.util.List;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

/**
 *
 * @author Admin
 */
public class JavaMailUtil {

    public static void sendMail(String recepient, String subject, String mailContent) {
        Properties properties = new Properties();
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.smtp.host", "smtp.gmail.com");
        properties.put("mail.smtp.port", "587");

        String myAccount = "east2westtoursandtravels@gmail.com";
        String password = "phamhoangtam";

        Session session = Session.getInstance(properties, new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(myAccount, password);
            }
        });

        Message message = prepareMessage(session, myAccount, recepient, subject, mailContent);
        try {
            Transport.send(message);
        } catch (MessagingException ex) {
            Logger.getLogger(JavaMailUtil.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private static Message prepareMessage(Session session, String accountEmail, String recepient, String subject, String content) {
        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(accountEmail));
            message.setRecipient(Message.RecipientType.TO, new InternetAddress(recepient));
            message.setSubject(subject);
            message.setContent(content, "text/html");
            return message;
        } catch (MessagingException ex) {
            Logger.getLogger(JavaMailUtil.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    public static String createSignedUpMessage(String name) {
        return "<!doctype html>\n"
                + "<html>\n"
                + "  <head>\n"
                + "    <meta name=\"viewport\" content=\"width=device-width\" />\n"
                + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n"
                + "    <title>Simple Transactional Email</title>\n"
                + "    <style>\n"
                + "      /* -------------------------------------\n"
                + "          GLOBAL RESETS\n"
                + "      ------------------------------------- */\n"
                + "      \n"
                + "      /*All the styling goes here*/\n"
                + "      \n"
                + "      img {\n"
                + "        border: none;\n"
                + "        -ms-interpolation-mode: bicubic;\n"
                + "        max-width: 100%; \n"
                + "      }\n"
                + "\n"
                + "      body {\n"
                + "        background-color: #f6f6f6;\n"
                + "        font-family: sans-serif;\n"
                + "        -webkit-font-smoothing: antialiased;\n"
                + "        font-size: 14px;\n"
                + "        line-height: 1.4;\n"
                + "        margin: 0;\n"
                + "        padding: 0;\n"
                + "        -ms-text-size-adjust: 100%;\n"
                + "        -webkit-text-size-adjust: 100%; \n"
                + "      }\n"
                + "\n"
                + "      table {\n"
                + "        border-collapse: separate;\n"
                + "        mso-table-lspace: 0pt;\n"
                + "        mso-table-rspace: 0pt;\n"
                + "        width: 100%; }\n"
                + "        table td {\n"
                + "          font-family: sans-serif;\n"
                + "          font-size: 14px;\n"
                + "          vertical-align: top; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          BODY & CONTAINER\n"
                + "      ------------------------------------- */\n"
                + "\n"
                + "      .body {\n"
                + "        background-color: #f6f6f6;\n"
                + "        width: 100%; \n"
                + "      }\n"
                + "\n"
                + "      /* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */\n"
                + "      .container {\n"
                + "        display: block;\n"
                + "        margin: 0 auto !important;\n"
                + "        /* makes it centered */\n"
                + "        max-width: 580px;\n"
                + "        padding: 10px;\n"
                + "        width: 580px; \n"
                + "      }\n"
                + "\n"
                + "      /* This should also be a block element, so that it will fill 100% of the .container */\n"
                + "      .content {\n"
                + "        box-sizing: border-box;\n"
                + "        display: block;\n"
                + "        margin: 0 auto;\n"
                + "        max-width: 580px;\n"
                + "        padding: 10px; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          HEADER, FOOTER, MAIN\n"
                + "      ------------------------------------- */\n"
                + "      .main {\n"
                + "        background: #ffffff;\n"
                + "        border-radius: 3px;\n"
                + "        width: 100%; \n"
                + "      }\n"
                + "\n"
                + "      .wrapper {\n"
                + "        box-sizing: border-box;\n"
                + "        padding: 20px; \n"
                + "      }\n"
                + "\n"
                + "      .content-block {\n"
                + "        padding-bottom: 10px;\n"
                + "        padding-top: 10px;\n"
                + "      }\n"
                + "\n"
                + "      .footer {\n"
                + "        clear: both;\n"
                + "        margin-top: 10px;\n"
                + "        text-align: center;\n"
                + "        width: 100%; \n"
                + "      }\n"
                + "        .footer td,\n"
                + "        .footer p,\n"
                + "        .footer span,\n"
                + "        .footer a {\n"
                + "          color: #999999;\n"
                + "          font-size: 12px;\n"
                + "          text-align: center; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          TYPOGRAPHY\n"
                + "      ------------------------------------- */\n"
                + "      h1,\n"
                + "      h2,\n"
                + "      h3,\n"
                + "      h4 {\n"
                + "        color: #000000;\n"
                + "        font-family: sans-serif;\n"
                + "        font-weight: 400;\n"
                + "        line-height: 1.4;\n"
                + "        margin: 0;\n"
                + "        margin-bottom: 30px; \n"
                + "      }\n"
                + "\n"
                + "      h1 {\n"
                + "        font-size: 35px;\n"
                + "        font-weight: 300;\n"
                + "        text-align: center;\n"
                + "        text-transform: capitalize; \n"
                + "      }\n"
                + "\n"
                + "      p,\n"
                + "      ul,\n"
                + "      ol {\n"
                + "        font-family: sans-serif;\n"
                + "        font-size: 14px;\n"
                + "        font-weight: normal;\n"
                + "        margin: 0;\n"
                + "        margin-bottom: 15px; \n"
                + "      }\n"
                + "        p li,\n"
                + "        ul li,\n"
                + "        ol li {\n"
                + "          list-style-position: inside;\n"
                + "          margin-left: 5px; \n"
                + "      }\n"
                + "\n"
                + "      a {\n"
                + "        color: #3498db;\n"
                + "        text-decoration: underline; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          BUTTONS\n"
                + "      ------------------------------------- */\n"
                + "      .btn {\n"
                + "        box-sizing: border-box;\n"
                + "        width: 100%; }\n"
                + "        .btn > tbody > tr > td {\n"
                + "          padding-bottom: 15px; }\n"
                + "        .btn table {\n"
                + "          width: auto; \n"
                + "      }\n"
                + "        .btn table td {\n"
                + "          background-color: #ffffff;\n"
                + "          border-radius: 5px;\n"
                + "          text-align: center; \n"
                + "      }\n"
                + "        .btn a {\n"
                + "          background-color: #ffffff;\n"
                + "          border: solid 1px #3498db;\n"
                + "          border-radius: 5px;\n"
                + "          box-sizing: border-box;\n"
                + "          color: #3498db;\n"
                + "          cursor: pointer;\n"
                + "          display: inline-block;\n"
                + "          font-size: 14px;\n"
                + "          font-weight: bold;\n"
                + "          margin: 0;\n"
                + "          padding: 12px 25px;\n"
                + "          text-decoration: none;\n"
                + "          text-transform: capitalize; \n"
                + "      }\n"
                + "\n"
                + "      .btn-primary table td {\n"
                + "        background-color: #3498db; \n"
                + "      }\n"
                + "\n"
                + "      .btn-primary a {\n"
                + "        background-color: #3498db;\n"
                + "        border-color: #3498db;\n"
                + "        color: #ffffff; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          OTHER STYLES THAT MIGHT BE USEFUL\n"
                + "      ------------------------------------- */\n"
                + "      .last {\n"
                + "        margin-bottom: 0; \n"
                + "      }\n"
                + "\n"
                + "      .first {\n"
                + "        margin-top: 0; \n"
                + "      }\n"
                + "\n"
                + "      .align-center {\n"
                + "        text-align: center; \n"
                + "      }\n"
                + "\n"
                + "      .align-right {\n"
                + "        text-align: right; \n"
                + "      }\n"
                + "\n"
                + "      .align-left {\n"
                + "        text-align: left; \n"
                + "      }\n"
                + "\n"
                + "      .clear {\n"
                + "        clear: both; \n"
                + "      }\n"
                + "\n"
                + "      .mt0 {\n"
                + "        margin-top: 0; \n"
                + "      }\n"
                + "\n"
                + "      .mb0 {\n"
                + "        margin-bottom: 0; \n"
                + "      }\n"
                + "\n"
                + "      .preheader {\n"
                + "        color: transparent;\n"
                + "        display: none;\n"
                + "        height: 0;\n"
                + "        max-height: 0;\n"
                + "        max-width: 0;\n"
                + "        opacity: 0;\n"
                + "        overflow: hidden;\n"
                + "        mso-hide: all;\n"
                + "        visibility: hidden;\n"
                + "        width: 0; \n"
                + "      }\n"
                + "\n"
                + "      .powered-by a {\n"
                + "        text-decoration: none; \n"
                + "      }\n"
                + "\n"
                + "      hr {\n"
                + "        border: 0;\n"
                + "        border-bottom: 1px solid #f6f6f6;\n"
                + "        margin: 20px 0; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          RESPONSIVE AND MOBILE FRIENDLY STYLES\n"
                + "      ------------------------------------- */\n"
                + "      @media only screen and (max-width: 620px) {\n"
                + "        table[class=body] h1 {\n"
                + "          font-size: 28px !important;\n"
                + "          margin-bottom: 10px !important; \n"
                + "        }\n"
                + "        table[class=body] p,\n"
                + "        table[class=body] ul,\n"
                + "        table[class=body] ol,\n"
                + "        table[class=body] td,\n"
                + "        table[class=body] span,\n"
                + "        table[class=body] a {\n"
                + "          font-size: 16px !important; \n"
                + "        }\n"
                + "        table[class=body] .wrapper,\n"
                + "        table[class=body] .article {\n"
                + "          padding: 10px !important; \n"
                + "        }\n"
                + "        table[class=body] .content {\n"
                + "          padding: 0 !important; \n"
                + "        }\n"
                + "        table[class=body] .container {\n"
                + "          padding: 0 !important;\n"
                + "          width: 100% !important; \n"
                + "        }\n"
                + "        table[class=body] .main {\n"
                + "          border-left-width: 0 !important;\n"
                + "          border-radius: 0 !important;\n"
                + "          border-right-width: 0 !important; \n"
                + "        }\n"
                + "        table[class=body] .btn table {\n"
                + "          width: 100% !important; \n"
                + "        }\n"
                + "        table[class=body] .btn a {\n"
                + "          width: 100% !important; \n"
                + "        }\n"
                + "        table[class=body] .img-responsive {\n"
                + "          height: auto !important;\n"
                + "          max-width: 100% !important;\n"
                + "          width: auto !important; \n"
                + "        }\n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          PRESERVE THESE STYLES IN THE HEAD\n"
                + "      ------------------------------------- */\n"
                + "      @media all {\n"
                + "        .ExternalClass {\n"
                + "          width: 100%; \n"
                + "        }\n"
                + "        .ExternalClass,\n"
                + "        .ExternalClass p,\n"
                + "        .ExternalClass span,\n"
                + "        .ExternalClass font,\n"
                + "        .ExternalClass td,\n"
                + "        .ExternalClass div {\n"
                + "          line-height: 100%; \n"
                + "        }\n"
                + "        .apple-link a {\n"
                + "          color: inherit !important;\n"
                + "          font-family: inherit !important;\n"
                + "          font-size: inherit !important;\n"
                + "          font-weight: inherit !important;\n"
                + "          line-height: inherit !important;\n"
                + "          text-decoration: none !important; \n"
                + "        }\n"
                + "        #MessageViewBody a {\n"
                + "          color: inherit;\n"
                + "          text-decoration: none;\n"
                + "          font-size: inherit;\n"
                + "          font-family: inherit;\n"
                + "          font-weight: inherit;\n"
                + "          line-height: inherit;\n"
                + "        }\n"
                + "        .btn-primary table td:hover {\n"
                + "          background-color: #34495e !important; \n"
                + "        }\n"
                + "        .btn-primary a:hover {\n"
                + "          background-color: #34495e !important;\n"
                + "          border-color: #34495e !important; \n"
                + "        } \n"
                + "      }\n"
                + "\n"
                + "    </style>\n"
                + "  </head>\n"
                + "  <body class=\"\">\n"
                + "    <span class=\"preheader\"></span>\n"
                + "    <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"body\">\n"
                + "      <tr>\n"
                + "        <td>&nbsp;</td>\n"
                + "        <td class=\"container\">\n"
                + "          <div class=\"content\">\n"
                + "\n"
                + "            <!-- START CENTERED WHITE CONTAINER -->\n"
                + "            <table role=\"presentation\" class=\"main\">\n"
                + "\n"
                + "              <!-- START MAIN CONTENT AREA -->\n"
                + "              <tr>\n"
                + "                <td class=\"wrapper\">\n"
                + "                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                    <tr>\n"
                + "                      <td>\n"
                + "                        <p>Welcome <b>" + name + "</b>,</p>\n"
                + "                        <p>Your account has been registered successfully at <b>East 2 West Tours and Travels</b> website.</p>\n"
                + "                        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"btn btn-primary\">\n"
                + "                          <tbody>\n"
                + "                            <tr>\n"
                + "                              <td align=\"left\">\n"
                + "                                <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                                  <tbody>\n"
                + "                                    <tr>\n"
                + "                                      <td> <a href=\"#\" target=\"_blank\">Back to website</a> </td>\n"
                + "                                    </tr>\n"
                + "                                  </tbody>\n"
                + "                                </table>\n"
                + "                              </td>\n"
                + "                            </tr>\n"
                + "                          </tbody>\n"
                + "                        </table>\n"
                + "                        <p>We wish you a relaxing and enjoyable travels.</p>\n"
                + "                        <p>Thank for visiting our website.</p>\n"
                + "                      </td>\n"
                + "                    </tr>\n"
                + "                  </table>\n"
                + "                </td>\n"
                + "              </tr>\n"
                + "\n"
                + "            <!-- END MAIN CONTENT AREA -->\n"
                + "            </table>\n"
                + "            <!-- END CENTERED WHITE CONTAINER -->\n"
                + "\n"
                + "            <!-- START FOOTER -->\n"
                + "            <div class=\"footer\">\n"
                + "              <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                <tr>\n"
                + "                  <td class=\"content-block\">\n"
                + "                    <span class=\"apple-link\"></span>\n"
                + "                    \n"
                + "                  </td>\n"
                + "                </tr>\n"
                + "                <tr>\n"
                + "                  <td class=\"content-block powered-by\">\n"
                + "                    East 2 West Tours and Travels.\n"
                + "                  </td>\n"
                + "                </tr>\n"
                + "              </table>\n"
                + "            </div>\n"
                + "            <!-- END FOOTER -->\n"
                + "\n"
                + "          </div>\n"
                + "        </td>\n"
                + "        <td>&nbsp;</td>\n"
                + "      </tr>\n"
                + "    </table>\n"
                + "  </body>\n"
                + "</html>";
    }

    public static String createPlacedOrderMessage(String name, List<TourRegistration> td, List<CarRegistrationDetails> crd) {
        String tour = "";
        String car = "";
        long total = 0;
        if (td.size() > 0) {
            for (TourRegistration item : td) {
                tour += "<tr><td>" + item.getTourId().getTourName() + "</td><td>x " + item.getQuantity() + "</td><td>" + (item.getQuantity() * item.getTourId().getUnitPrice().longValue()) + " VND</td></tr>";
                total += (item.getQuantity() * item.getTourId().getUnitPrice().longValue());
            }
        }
        if (crd.size() > 0) {
            for (CarRegistrationDetails item : crd) {
                tour += "<tr><td>" + item.getCars().getCarName()+ "</td><td>x " + item.getQuantity() + "</td><td>" + (item.getQuantity() * item.getCars().getUnitPrice().longValue()) + " VND</td></tr>";
                total += (item.getQuantity() * item.getCars().getUnitPrice().longValue());
            }
        }

        return "<!doctype html>\n"
                + "<html>\n"
                + "  <head>\n"
                + "    <meta name=\"viewport\" content=\"width=device-width\" />\n"
                + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n"
                + "    <title>Simple Transactional Email</title>\n"
                + "    <style>\n"
                + "      /* -------------------------------------\n"
                + "          GLOBAL RESETS\n"
                + "      ------------------------------------- */\n"
                + "      \n"
                + "      /*All the styling goes here*/\n"
                + "      \n"
                + "      img {\n"
                + "        border: none;\n"
                + "        -ms-interpolation-mode: bicubic;\n"
                + "        max-width: 100%; \n"
                + "      }\n"
                + "\n"
                + "      body {\n"
                + "        background-color: #f6f6f6;\n"
                + "        font-family: sans-serif;\n"
                + "        -webkit-font-smoothing: antialiased;\n"
                + "        font-size: 14px;\n"
                + "        line-height: 1.4;\n"
                + "        margin: 0;\n"
                + "        padding: 0;\n"
                + "        -ms-text-size-adjust: 100%;\n"
                + "        -webkit-text-size-adjust: 100%; \n"
                + "      }\n"
                + "\n"
                + "      table {\n"
                + "        border-collapse: separate;\n"
                + "        mso-table-lspace: 0pt;\n"
                + "        mso-table-rspace: 0pt;\n"
                + "        width: 100%; }\n"
                + "        table td {\n"
                + "          font-family: sans-serif;\n"
                + "          font-size: 14px;\n"
                + "          vertical-align: top; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          BODY & CONTAINER\n"
                + "      ------------------------------------- */\n"
                + "\n"
                + "      .body {\n"
                + "        background-color: #f6f6f6;\n"
                + "        width: 100%; \n"
                + "      }\n"
                + "\n"
                + "      /* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */\n"
                + "      .container {\n"
                + "        display: block;\n"
                + "        margin: 0 auto !important;\n"
                + "        /* makes it centered */\n"
                + "        max-width: 580px;\n"
                + "        padding: 10px;\n"
                + "        width: 580px; \n"
                + "      }\n"
                + "\n"
                + "      /* This should also be a block element, so that it will fill 100% of the .container */\n"
                + "      .content {\n"
                + "        box-sizing: border-box;\n"
                + "        display: block;\n"
                + "        margin: 0 auto;\n"
                + "        max-width: 580px;\n"
                + "        padding: 10px; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          HEADER, FOOTER, MAIN\n"
                + "      ------------------------------------- */\n"
                + "      .main {\n"
                + "        background: #ffffff;\n"
                + "        border-radius: 3px;\n"
                + "        width: 100%; \n"
                + "      }\n"
                + "\n"
                + "      .wrapper {\n"
                + "        box-sizing: border-box;\n"
                + "        padding: 20px; \n"
                + "      }\n"
                + "\n"
                + "      .content-block {\n"
                + "        padding-bottom: 10px;\n"
                + "        padding-top: 10px;\n"
                + "      }\n"
                + "\n"
                + "      .footer {\n"
                + "        clear: both;\n"
                + "        margin-top: 10px;\n"
                + "        text-align: center;\n"
                + "        width: 100%; \n"
                + "      }\n"
                + "        .footer td,\n"
                + "        .footer p,\n"
                + "        .footer span,\n"
                + "        .footer a {\n"
                + "          color: #999999;\n"
                + "          font-size: 12px;\n"
                + "          text-align: center; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          TYPOGRAPHY\n"
                + "      ------------------------------------- */\n"
                + "      h1,\n"
                + "      h2,\n"
                + "      h3,\n"
                + "      h4 {\n"
                + "        color: #000000;\n"
                + "        font-family: sans-serif;\n"
                + "        font-weight: 400;\n"
                + "        line-height: 1.4;\n"
                + "        margin: 0;\n"
                + "        margin-bottom: 30px; \n"
                + "      }\n"
                + "\n"
                + "      h1 {\n"
                + "        font-size: 35px;\n"
                + "        font-weight: 300;\n"
                + "        text-align: center;\n"
                + "        text-transform: capitalize; \n"
                + "      }\n"
                + "\n"
                + "      p,\n"
                + "      ul,\n"
                + "      ol {\n"
                + "        font-family: sans-serif;\n"
                + "        font-size: 14px;\n"
                + "        font-weight: normal;\n"
                + "        margin: 0;\n"
                + "        margin-bottom: 15px; \n"
                + "      }\n"
                + "        p li,\n"
                + "        ul li,\n"
                + "        ol li {\n"
                + "          list-style-position: inside;\n"
                + "          margin-left: 5px; \n"
                + "      }\n"
                + "\n"
                + "      a {\n"
                + "        color: #3498db;\n"
                + "        text-decoration: underline; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          BUTTONS\n"
                + "      ------------------------------------- */\n"
                + "      .btn {\n"
                + "        box-sizing: border-box;\n"
                + "        width: 100%; }\n"
                + "        .btn > tbody > tr > td {\n"
                + "          padding-bottom: 15px; }\n"
                + "        .btn table {\n"
                + "          width: auto; \n"
                + "      }\n"
                + "        .btn table td {\n"
                + "          background-color: #ffffff;\n"
                + "          border-radius: 5px;\n"
                + "          text-align: center; \n"
                + "      }\n"
                + "        .btn a {\n"
                + "          background-color: #ffffff;\n"
                + "          border: solid 1px #3498db;\n"
                + "          border-radius: 5px;\n"
                + "          box-sizing: border-box;\n"
                + "          color: #3498db;\n"
                + "          cursor: pointer;\n"
                + "          display: inline-block;\n"
                + "          font-size: 14px;\n"
                + "          font-weight: bold;\n"
                + "          margin: 0;\n"
                + "          padding: 12px 25px;\n"
                + "          text-decoration: none;\n"
                + "          text-transform: capitalize; \n"
                + "      }\n"
                + "\n"
                + "      .btn-primary table td {\n"
                + "        background-color: #3498db; \n"
                + "      }\n"
                + "\n"
                + "      .btn-primary a {\n"
                + "        background-color: #3498db;\n"
                + "        border-color: #3498db;\n"
                + "        color: #ffffff; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          OTHER STYLES THAT MIGHT BE USEFUL\n"
                + "      ------------------------------------- */\n"
                + "      .last {\n"
                + "        margin-bottom: 0; \n"
                + "      }\n"
                + "\n"
                + "      .first {\n"
                + "        margin-top: 0; \n"
                + "      }\n"
                + "\n"
                + "      .align-center {\n"
                + "        text-align: center; \n"
                + "      }\n"
                + "\n"
                + "      .align-right {\n"
                + "        text-align: right; \n"
                + "      }\n"
                + "\n"
                + "      .align-left {\n"
                + "        text-align: left; \n"
                + "      }\n"
                + "\n"
                + "      .clear {\n"
                + "        clear: both; \n"
                + "      }\n"
                + "\n"
                + "      .mt0 {\n"
                + "        margin-top: 0; \n"
                + "      }\n"
                + "\n"
                + "      .mb0 {\n"
                + "        margin-bottom: 0; \n"
                + "      }\n"
                + "\n"
                + "      .preheader {\n"
                + "        color: transparent;\n"
                + "        display: none;\n"
                + "        height: 0;\n"
                + "        max-height: 0;\n"
                + "        max-width: 0;\n"
                + "        opacity: 0;\n"
                + "        overflow: hidden;\n"
                + "        mso-hide: all;\n"
                + "        visibility: hidden;\n"
                + "        width: 0; \n"
                + "      }\n"
                + "\n"
                + "      .powered-by a {\n"
                + "        text-decoration: none; \n"
                + "      }\n"
                + "\n"
                + "      hr {\n"
                + "        border: 0;\n"
                + "        border-bottom: 1px solid #f6f6f6;\n"
                + "        margin: 20px 0; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          RESPONSIVE AND MOBILE FRIENDLY STYLES\n"
                + "      ------------------------------------- */\n"
                + "      @media only screen and (max-width: 620px) {\n"
                + "        table[class=body] h1 {\n"
                + "          font-size: 28px !important;\n"
                + "          margin-bottom: 10px !important; \n"
                + "        }\n"
                + "        table[class=body] p,\n"
                + "        table[class=body] ul,\n"
                + "        table[class=body] ol,\n"
                + "        table[class=body] td,\n"
                + "        table[class=body] span,\n"
                + "        table[class=body] a {\n"
                + "          font-size: 16px !important; \n"
                + "        }\n"
                + "        table[class=body] .wrapper,\n"
                + "        table[class=body] .article {\n"
                + "          padding: 10px !important; \n"
                + "        }\n"
                + "        table[class=body] .content {\n"
                + "          padding: 0 !important; \n"
                + "        }\n"
                + "        table[class=body] .container {\n"
                + "          padding: 0 !important;\n"
                + "          width: 100% !important; \n"
                + "        }\n"
                + "        table[class=body] .main {\n"
                + "          border-left-width: 0 !important;\n"
                + "          border-radius: 0 !important;\n"
                + "          border-right-width: 0 !important; \n"
                + "        }\n"
                + "        table[class=body] .btn table {\n"
                + "          width: 100% !important; \n"
                + "        }\n"
                + "        table[class=body] .btn a {\n"
                + "          width: 100% !important; \n"
                + "        }\n"
                + "        table[class=body] .img-responsive {\n"
                + "          height: auto !important;\n"
                + "          max-width: 100% !important;\n"
                + "          width: auto !important; \n"
                + "        }\n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          PRESERVE THESE STYLES IN THE HEAD\n"
                + "      ------------------------------------- */\n"
                + "      @media all {\n"
                + "        .ExternalClass {\n"
                + "          width: 100%; \n"
                + "        }\n"
                + "        .ExternalClass,\n"
                + "        .ExternalClass p,\n"
                + "        .ExternalClass span,\n"
                + "        .ExternalClass font,\n"
                + "        .ExternalClass td,\n"
                + "        .ExternalClass div {\n"
                + "          line-height: 100%; \n"
                + "        }\n"
                + "        .apple-link a {\n"
                + "          color: inherit !important;\n"
                + "          font-family: inherit !important;\n"
                + "          font-size: inherit !important;\n"
                + "          font-weight: inherit !important;\n"
                + "          line-height: inherit !important;\n"
                + "          text-decoration: none !important; \n"
                + "        }\n"
                + "        #MessageViewBody a {\n"
                + "          color: inherit;\n"
                + "          text-decoration: none;\n"
                + "          font-size: inherit;\n"
                + "          font-family: inherit;\n"
                + "          font-weight: inherit;\n"
                + "          line-height: inherit;\n"
                + "        }\n"
                + "        .btn-primary table td:hover {\n"
                + "          background-color: #34495e !important; \n"
                + "        }\n"
                + "        .btn-primary a:hover {\n"
                + "          background-color: #34495e !important;\n"
                + "          border-color: #34495e !important; \n"
                + "        } \n"
                + "      }\n"
                + "\n"
                + "    </style>\n"
                + "  </head>\n"
                + "  <body class=\"\">\n"
                + "    <span class=\"preheader\"></span>\n"
                + "    <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"body\">\n"
                + "      <tr>\n"
                + "        <td>&nbsp;</td>\n"
                + "        <td class=\"container\">\n"
                + "          <div class=\"content\">\n"
                + "\n"
                + "            <!-- START CENTERED WHITE CONTAINER -->\n"
                + "            <table role=\"presentation\" class=\"main\">\n"
                + "\n"
                + "              <!-- START MAIN CONTENT AREA -->\n"
                + "              <tr>\n"
                + "                <td class=\"wrapper\">\n"
                + "                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                    <tr>\n"
                + "                      <td>\n"
                + "                        <p>Hi <b>" + name + "</b>,</p>\n"
                + "                        <p>We wish you a relaxing and enjoyable travels. Your order will be handled as soon as possible by our staff.</p>\n"
                + "                        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"btn btn-primary\" >\n"
                + "                          <tbody>\n"
                + "                            <tr>\n"
                + "                              <td align=\"left\">\n"
                + "                                <table style=\"width:100%\" role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                                  <tbody>\n"
                + tour + car
                + "                                  </tbody>\n"
                + "                                </table>\n"
                + "                              </td>\n"
                + "                            </tr>\n"
                + "                          </tbody>\n"
                + "                        </table>\n"
                + "                        <p><b>TOTAL: </b>" + total + " VND</p>\n"
                + "                        <p>Thank for visiting our website.</p>\n"
                + "                      </td>\n"
                + "                    </tr>\n"
                + "                  </table>\n"
                + "                </td>\n"
                + "              </tr>\n"
                + "\n"
                + "            <!-- END MAIN CONTENT AREA -->\n"
                + "            </table>\n"
                + "            <!-- END CENTERED WHITE CONTAINER -->\n"
                + "\n"
                + "            <!-- START FOOTER -->\n"
                + "            <div class=\"footer\">\n"
                + "              <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                <tr>\n"
                + "                  <td class=\"content-block\">\n"
                + "                    <span class=\"apple-link\"></span>\n"
                + "                    \n"
                + "                  </td>\n"
                + "                </tr>\n"
                + "                <tr>\n"
                + "                  <td class=\"content-block powered-by\">\n"
                + "                    East 2 West Tours and Travels.\n"
                + "                  </td>\n"
                + "                </tr>\n"
                + "              </table>\n"
                + "            </div>\n"
                + "            <!-- END FOOTER -->\n"
                + "\n"
                + "          </div>\n"
                + "        </td>\n"
                + "        <td>&nbsp;</td>\n"
                + "      </tr>\n"
                + "    </table>\n"
                + "  </body>\n"
                + "</html>";
    }
    
    public static String createApprovedTourRegistrationMessage(String name, String tourName, String registrationDate, String departure) {
        return "<!doctype html>\n"
                + "<html>\n"
                + "  <head>\n"
                + "    <meta name=\"viewport\" content=\"width=device-width\" />\n"
                + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n"
                + "    <title>Simple Transactional Email</title>\n"
                + "    <style>\n"
                + "      /* -------------------------------------\n"
                + "          GLOBAL RESETS\n"
                + "      ------------------------------------- */\n"
                + "      \n"
                + "      /*All the styling goes here*/\n"
                + "      \n"
                + "      img {\n"
                + "        border: none;\n"
                + "        -ms-interpolation-mode: bicubic;\n"
                + "        max-width: 100%; \n"
                + "      }\n"
                + "\n"
                + "      body {\n"
                + "        background-color: #f6f6f6;\n"
                + "        font-family: sans-serif;\n"
                + "        -webkit-font-smoothing: antialiased;\n"
                + "        font-size: 14px;\n"
                + "        line-height: 1.4;\n"
                + "        margin: 0;\n"
                + "        padding: 0;\n"
                + "        -ms-text-size-adjust: 100%;\n"
                + "        -webkit-text-size-adjust: 100%; \n"
                + "      }\n"
                + "\n"
                + "      table {\n"
                + "        border-collapse: separate;\n"
                + "        mso-table-lspace: 0pt;\n"
                + "        mso-table-rspace: 0pt;\n"
                + "        width: 100%; }\n"
                + "        table td {\n"
                + "          font-family: sans-serif;\n"
                + "          font-size: 14px;\n"
                + "          vertical-align: top; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          BODY & CONTAINER\n"
                + "      ------------------------------------- */\n"
                + "\n"
                + "      .body {\n"
                + "        background-color: #f6f6f6;\n"
                + "        width: 100%; \n"
                + "      }\n"
                + "\n"
                + "      /* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */\n"
                + "      .container {\n"
                + "        display: block;\n"
                + "        margin: 0 auto !important;\n"
                + "        /* makes it centered */\n"
                + "        max-width: 580px;\n"
                + "        padding: 10px;\n"
                + "        width: 580px; \n"
                + "      }\n"
                + "\n"
                + "      /* This should also be a block element, so that it will fill 100% of the .container */\n"
                + "      .content {\n"
                + "        box-sizing: border-box;\n"
                + "        display: block;\n"
                + "        margin: 0 auto;\n"
                + "        max-width: 580px;\n"
                + "        padding: 10px; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          HEADER, FOOTER, MAIN\n"
                + "      ------------------------------------- */\n"
                + "      .main {\n"
                + "        background: #ffffff;\n"
                + "        border-radius: 3px;\n"
                + "        width: 100%; \n"
                + "      }\n"
                + "\n"
                + "      .wrapper {\n"
                + "        box-sizing: border-box;\n"
                + "        padding: 20px; \n"
                + "      }\n"
                + "\n"
                + "      .content-block {\n"
                + "        padding-bottom: 10px;\n"
                + "        padding-top: 10px;\n"
                + "      }\n"
                + "\n"
                + "      .footer {\n"
                + "        clear: both;\n"
                + "        margin-top: 10px;\n"
                + "        text-align: center;\n"
                + "        width: 100%; \n"
                + "      }\n"
                + "        .footer td,\n"
                + "        .footer p,\n"
                + "        .footer span,\n"
                + "        .footer a {\n"
                + "          color: #999999;\n"
                + "          font-size: 12px;\n"
                + "          text-align: center; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          TYPOGRAPHY\n"
                + "      ------------------------------------- */\n"
                + "      h1,\n"
                + "      h2,\n"
                + "      h3,\n"
                + "      h4 {\n"
                + "        color: #000000;\n"
                + "        font-family: sans-serif;\n"
                + "        font-weight: 400;\n"
                + "        line-height: 1.4;\n"
                + "        margin: 0;\n"
                + "        margin-bottom: 30px; \n"
                + "      }\n"
                + "\n"
                + "      h1 {\n"
                + "        font-size: 35px;\n"
                + "        font-weight: 300;\n"
                + "        text-align: center;\n"
                + "        text-transform: capitalize; \n"
                + "      }\n"
                + "\n"
                + "      p,\n"
                + "      ul,\n"
                + "      ol {\n"
                + "        font-family: sans-serif;\n"
                + "        font-size: 14px;\n"
                + "        font-weight: normal;\n"
                + "        margin: 0;\n"
                + "        margin-bottom: 15px; \n"
                + "      }\n"
                + "        p li,\n"
                + "        ul li,\n"
                + "        ol li {\n"
                + "          list-style-position: inside;\n"
                + "          margin-left: 5px; \n"
                + "      }\n"
                + "\n"
                + "      a {\n"
                + "        color: #3498db;\n"
                + "        text-decoration: underline; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          BUTTONS\n"
                + "      ------------------------------------- */\n"
                + "      .btn {\n"
                + "        box-sizing: border-box;\n"
                + "        width: 100%; }\n"
                + "        .btn > tbody > tr > td {\n"
                + "          padding-bottom: 15px; }\n"
                + "        .btn table {\n"
                + "          width: auto; \n"
                + "      }\n"
                + "        .btn table td {\n"
                + "          background-color: #ffffff;\n"
                + "          border-radius: 5px;\n"
                + "          text-align: center; \n"
                + "      }\n"
                + "        .btn a {\n"
                + "          background-color: #ffffff;\n"
                + "          border: solid 1px #3498db;\n"
                + "          border-radius: 5px;\n"
                + "          box-sizing: border-box;\n"
                + "          color: #3498db;\n"
                + "          cursor: pointer;\n"
                + "          display: inline-block;\n"
                + "          font-size: 14px;\n"
                + "          font-weight: bold;\n"
                + "          margin: 0;\n"
                + "          padding: 12px 25px;\n"
                + "          text-decoration: none;\n"
                + "          text-transform: capitalize; \n"
                + "      }\n"
                + "\n"
                + "      .btn-primary table td {\n"
                + "        background-color: #3498db; \n"
                + "      }\n"
                + "\n"
                + "      .btn-primary a {\n"
                + "        background-color: #3498db;\n"
                + "        border-color: #3498db;\n"
                + "        color: #ffffff; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          OTHER STYLES THAT MIGHT BE USEFUL\n"
                + "      ------------------------------------- */\n"
                + "      .last {\n"
                + "        margin-bottom: 0; \n"
                + "      }\n"
                + "\n"
                + "      .first {\n"
                + "        margin-top: 0; \n"
                + "      }\n"
                + "\n"
                + "      .align-center {\n"
                + "        text-align: center; \n"
                + "      }\n"
                + "\n"
                + "      .align-right {\n"
                + "        text-align: right; \n"
                + "      }\n"
                + "\n"
                + "      .align-left {\n"
                + "        text-align: left; \n"
                + "      }\n"
                + "\n"
                + "      .clear {\n"
                + "        clear: both; \n"
                + "      }\n"
                + "\n"
                + "      .mt0 {\n"
                + "        margin-top: 0; \n"
                + "      }\n"
                + "\n"
                + "      .mb0 {\n"
                + "        margin-bottom: 0; \n"
                + "      }\n"
                + "\n"
                + "      .preheader {\n"
                + "        color: transparent;\n"
                + "        display: none;\n"
                + "        height: 0;\n"
                + "        max-height: 0;\n"
                + "        max-width: 0;\n"
                + "        opacity: 0;\n"
                + "        overflow: hidden;\n"
                + "        mso-hide: all;\n"
                + "        visibility: hidden;\n"
                + "        width: 0; \n"
                + "      }\n"
                + "\n"
                + "      .powered-by a {\n"
                + "        text-decoration: none; \n"
                + "      }\n"
                + "\n"
                + "      hr {\n"
                + "        border: 0;\n"
                + "        border-bottom: 1px solid #f6f6f6;\n"
                + "        margin: 20px 0; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          RESPONSIVE AND MOBILE FRIENDLY STYLES\n"
                + "      ------------------------------------- */\n"
                + "      @media only screen and (max-width: 620px) {\n"
                + "        table[class=body] h1 {\n"
                + "          font-size: 28px !important;\n"
                + "          margin-bottom: 10px !important; \n"
                + "        }\n"
                + "        table[class=body] p,\n"
                + "        table[class=body] ul,\n"
                + "        table[class=body] ol,\n"
                + "        table[class=body] td,\n"
                + "        table[class=body] span,\n"
                + "        table[class=body] a {\n"
                + "          font-size: 16px !important; \n"
                + "        }\n"
                + "        table[class=body] .wrapper,\n"
                + "        table[class=body] .article {\n"
                + "          padding: 10px !important; \n"
                + "        }\n"
                + "        table[class=body] .content {\n"
                + "          padding: 0 !important; \n"
                + "        }\n"
                + "        table[class=body] .container {\n"
                + "          padding: 0 !important;\n"
                + "          width: 100% !important; \n"
                + "        }\n"
                + "        table[class=body] .main {\n"
                + "          border-left-width: 0 !important;\n"
                + "          border-radius: 0 !important;\n"
                + "          border-right-width: 0 !important; \n"
                + "        }\n"
                + "        table[class=body] .btn table {\n"
                + "          width: 100% !important; \n"
                + "        }\n"
                + "        table[class=body] .btn a {\n"
                + "          width: 100% !important; \n"
                + "        }\n"
                + "        table[class=body] .img-responsive {\n"
                + "          height: auto !important;\n"
                + "          max-width: 100% !important;\n"
                + "          width: auto !important; \n"
                + "        }\n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          PRESERVE THESE STYLES IN THE HEAD\n"
                + "      ------------------------------------- */\n"
                + "      @media all {\n"
                + "        .ExternalClass {\n"
                + "          width: 100%; \n"
                + "        }\n"
                + "        .ExternalClass,\n"
                + "        .ExternalClass p,\n"
                + "        .ExternalClass span,\n"
                + "        .ExternalClass font,\n"
                + "        .ExternalClass td,\n"
                + "        .ExternalClass div {\n"
                + "          line-height: 100%; \n"
                + "        }\n"
                + "        .apple-link a {\n"
                + "          color: inherit !important;\n"
                + "          font-family: inherit !important;\n"
                + "          font-size: inherit !important;\n"
                + "          font-weight: inherit !important;\n"
                + "          line-height: inherit !important;\n"
                + "          text-decoration: none !important; \n"
                + "        }\n"
                + "        #MessageViewBody a {\n"
                + "          color: inherit;\n"
                + "          text-decoration: none;\n"
                + "          font-size: inherit;\n"
                + "          font-family: inherit;\n"
                + "          font-weight: inherit;\n"
                + "          line-height: inherit;\n"
                + "        }\n"
                + "        .btn-primary table td:hover {\n"
                + "          background-color: #34495e !important; \n"
                + "        }\n"
                + "        .btn-primary a:hover {\n"
                + "          background-color: #34495e !important;\n"
                + "          border-color: #34495e !important; \n"
                + "        } \n"
                + "      }\n"
                + "\n"
                + "    </style>\n"
                + "  </head>\n"
                + "  <body class=\"\">\n"
                + "    <span class=\"preheader\"></span>\n"
                + "    <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"body\">\n"
                + "      <tr>\n"
                + "        <td>&nbsp;</td>\n"
                + "        <td class=\"container\">\n"
                + "          <div class=\"content\">\n"
                + "\n"
                + "            <!-- START CENTERED WHITE CONTAINER -->\n"
                + "            <table role=\"presentation\" class=\"main\">\n"
                + "\n"
                + "              <!-- START MAIN CONTENT AREA -->\n"
                + "              <tr>\n"
                + "                <td class=\"wrapper\">\n"
                + "                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                    <tr>\n"
                + "                      <td>\n"
                + "                        <p>Congratulation <b>" + name + "</b>,</p>\n"
                + "                        <p>Your tour reservation: <b>"+tourName+"</b> at <b>"+registrationDate+"</b> has been approved.</p>\n"
                + "                        <p>The trip will begin in: <b>"+departure+"</b>.</p>\n"
                + "                        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"btn btn-primary\">\n"
                + "                          <tbody>\n"
                + "                            <tr>\n"
                + "                              <td align=\"left\">\n"
                + "                                <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                                  <tbody>\n"
                + "                                    <tr>\n"
                + "                                      <td> <a href=\"#\" target=\"_blank\">Back to website</a> </td>\n"
                + "                                    </tr>\n"
                + "                                  </tbody>\n"
                + "                                </table>\n"
                + "                              </td>\n"
                + "                            </tr>\n"
                + "                          </tbody>\n"
                + "                        </table>\n"
                + "                        <p>We wish you a relaxing and enjoyable travels.</p>\n"
                + "                        <p>Thank for visiting our website.</p>\n"
                + "                      </td>\n"
                + "                    </tr>\n"
                + "                  </table>\n"
                + "                </td>\n"
                + "              </tr>\n"
                + "\n"
                + "            <!-- END MAIN CONTENT AREA -->\n"
                + "            </table>\n"
                + "            <!-- END CENTERED WHITE CONTAINER -->\n"
                + "\n"
                + "            <!-- START FOOTER -->\n"
                + "            <div class=\"footer\">\n"
                + "              <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                <tr>\n"
                + "                  <td class=\"content-block\">\n"
                + "                    <span class=\"apple-link\"></span>\n"
                + "                    \n"
                + "                  </td>\n"
                + "                </tr>\n"
                + "                <tr>\n"
                + "                  <td class=\"content-block powered-by\">\n"
                + "                    East 2 West Tours and Travels.\n"
                + "                  </td>\n"
                + "                </tr>\n"
                + "              </table>\n"
                + "            </div>\n"
                + "            <!-- END FOOTER -->\n"
                + "\n"
                + "          </div>\n"
                + "        </td>\n"
                + "        <td>&nbsp;</td>\n"
                + "      </tr>\n"
                + "    </table>\n"
                + "  </body>\n"
                + "</html>";
    }
    
    public static String createCanceledTourRegistrationMessage(String name, String tourName, String registrationDate, String departure) {
        return "<!doctype html>\n"
                + "<html>\n"
                + "  <head>\n"
                + "    <meta name=\"viewport\" content=\"width=device-width\" />\n"
                + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n"
                + "    <title>Simple Transactional Email</title>\n"
                + "    <style>\n"
                + "      /* -------------------------------------\n"
                + "          GLOBAL RESETS\n"
                + "      ------------------------------------- */\n"
                + "      \n"
                + "      /*All the styling goes here*/\n"
                + "      \n"
                + "      img {\n"
                + "        border: none;\n"
                + "        -ms-interpolation-mode: bicubic;\n"
                + "        max-width: 100%; \n"
                + "      }\n"
                + "\n"
                + "      body {\n"
                + "        background-color: #f6f6f6;\n"
                + "        font-family: sans-serif;\n"
                + "        -webkit-font-smoothing: antialiased;\n"
                + "        font-size: 14px;\n"
                + "        line-height: 1.4;\n"
                + "        margin: 0;\n"
                + "        padding: 0;\n"
                + "        -ms-text-size-adjust: 100%;\n"
                + "        -webkit-text-size-adjust: 100%; \n"
                + "      }\n"
                + "\n"
                + "      table {\n"
                + "        border-collapse: separate;\n"
                + "        mso-table-lspace: 0pt;\n"
                + "        mso-table-rspace: 0pt;\n"
                + "        width: 100%; }\n"
                + "        table td {\n"
                + "          font-family: sans-serif;\n"
                + "          font-size: 14px;\n"
                + "          vertical-align: top; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          BODY & CONTAINER\n"
                + "      ------------------------------------- */\n"
                + "\n"
                + "      .body {\n"
                + "        background-color: #f6f6f6;\n"
                + "        width: 100%; \n"
                + "      }\n"
                + "\n"
                + "      /* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */\n"
                + "      .container {\n"
                + "        display: block;\n"
                + "        margin: 0 auto !important;\n"
                + "        /* makes it centered */\n"
                + "        max-width: 580px;\n"
                + "        padding: 10px;\n"
                + "        width: 580px; \n"
                + "      }\n"
                + "\n"
                + "      /* This should also be a block element, so that it will fill 100% of the .container */\n"
                + "      .content {\n"
                + "        box-sizing: border-box;\n"
                + "        display: block;\n"
                + "        margin: 0 auto;\n"
                + "        max-width: 580px;\n"
                + "        padding: 10px; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          HEADER, FOOTER, MAIN\n"
                + "      ------------------------------------- */\n"
                + "      .main {\n"
                + "        background: #ffffff;\n"
                + "        border-radius: 3px;\n"
                + "        width: 100%; \n"
                + "      }\n"
                + "\n"
                + "      .wrapper {\n"
                + "        box-sizing: border-box;\n"
                + "        padding: 20px; \n"
                + "      }\n"
                + "\n"
                + "      .content-block {\n"
                + "        padding-bottom: 10px;\n"
                + "        padding-top: 10px;\n"
                + "      }\n"
                + "\n"
                + "      .footer {\n"
                + "        clear: both;\n"
                + "        margin-top: 10px;\n"
                + "        text-align: center;\n"
                + "        width: 100%; \n"
                + "      }\n"
                + "        .footer td,\n"
                + "        .footer p,\n"
                + "        .footer span,\n"
                + "        .footer a {\n"
                + "          color: #999999;\n"
                + "          font-size: 12px;\n"
                + "          text-align: center; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          TYPOGRAPHY\n"
                + "      ------------------------------------- */\n"
                + "      h1,\n"
                + "      h2,\n"
                + "      h3,\n"
                + "      h4 {\n"
                + "        color: #000000;\n"
                + "        font-family: sans-serif;\n"
                + "        font-weight: 400;\n"
                + "        line-height: 1.4;\n"
                + "        margin: 0;\n"
                + "        margin-bottom: 30px; \n"
                + "      }\n"
                + "\n"
                + "      h1 {\n"
                + "        font-size: 35px;\n"
                + "        font-weight: 300;\n"
                + "        text-align: center;\n"
                + "        text-transform: capitalize; \n"
                + "      }\n"
                + "\n"
                + "      p,\n"
                + "      ul,\n"
                + "      ol {\n"
                + "        font-family: sans-serif;\n"
                + "        font-size: 14px;\n"
                + "        font-weight: normal;\n"
                + "        margin: 0;\n"
                + "        margin-bottom: 15px; \n"
                + "      }\n"
                + "        p li,\n"
                + "        ul li,\n"
                + "        ol li {\n"
                + "          list-style-position: inside;\n"
                + "          margin-left: 5px; \n"
                + "      }\n"
                + "\n"
                + "      a {\n"
                + "        color: #3498db;\n"
                + "        text-decoration: underline; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          BUTTONS\n"
                + "      ------------------------------------- */\n"
                + "      .btn {\n"
                + "        box-sizing: border-box;\n"
                + "        width: 100%; }\n"
                + "        .btn > tbody > tr > td {\n"
                + "          padding-bottom: 15px; }\n"
                + "        .btn table {\n"
                + "          width: auto; \n"
                + "      }\n"
                + "        .btn table td {\n"
                + "          background-color: #ffffff;\n"
                + "          border-radius: 5px;\n"
                + "          text-align: center; \n"
                + "      }\n"
                + "        .btn a {\n"
                + "          background-color: #ffffff;\n"
                + "          border: solid 1px #3498db;\n"
                + "          border-radius: 5px;\n"
                + "          box-sizing: border-box;\n"
                + "          color: #3498db;\n"
                + "          cursor: pointer;\n"
                + "          display: inline-block;\n"
                + "          font-size: 14px;\n"
                + "          font-weight: bold;\n"
                + "          margin: 0;\n"
                + "          padding: 12px 25px;\n"
                + "          text-decoration: none;\n"
                + "          text-transform: capitalize; \n"
                + "      }\n"
                + "\n"
                + "      .btn-primary table td {\n"
                + "        background-color: #3498db; \n"
                + "      }\n"
                + "\n"
                + "      .btn-primary a {\n"
                + "        background-color: #3498db;\n"
                + "        border-color: #3498db;\n"
                + "        color: #ffffff; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          OTHER STYLES THAT MIGHT BE USEFUL\n"
                + "      ------------------------------------- */\n"
                + "      .last {\n"
                + "        margin-bottom: 0; \n"
                + "      }\n"
                + "\n"
                + "      .first {\n"
                + "        margin-top: 0; \n"
                + "      }\n"
                + "\n"
                + "      .align-center {\n"
                + "        text-align: center; \n"
                + "      }\n"
                + "\n"
                + "      .align-right {\n"
                + "        text-align: right; \n"
                + "      }\n"
                + "\n"
                + "      .align-left {\n"
                + "        text-align: left; \n"
                + "      }\n"
                + "\n"
                + "      .clear {\n"
                + "        clear: both; \n"
                + "      }\n"
                + "\n"
                + "      .mt0 {\n"
                + "        margin-top: 0; \n"
                + "      }\n"
                + "\n"
                + "      .mb0 {\n"
                + "        margin-bottom: 0; \n"
                + "      }\n"
                + "\n"
                + "      .preheader {\n"
                + "        color: transparent;\n"
                + "        display: none;\n"
                + "        height: 0;\n"
                + "        max-height: 0;\n"
                + "        max-width: 0;\n"
                + "        opacity: 0;\n"
                + "        overflow: hidden;\n"
                + "        mso-hide: all;\n"
                + "        visibility: hidden;\n"
                + "        width: 0; \n"
                + "      }\n"
                + "\n"
                + "      .powered-by a {\n"
                + "        text-decoration: none; \n"
                + "      }\n"
                + "\n"
                + "      hr {\n"
                + "        border: 0;\n"
                + "        border-bottom: 1px solid #f6f6f6;\n"
                + "        margin: 20px 0; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          RESPONSIVE AND MOBILE FRIENDLY STYLES\n"
                + "      ------------------------------------- */\n"
                + "      @media only screen and (max-width: 620px) {\n"
                + "        table[class=body] h1 {\n"
                + "          font-size: 28px !important;\n"
                + "          margin-bottom: 10px !important; \n"
                + "        }\n"
                + "        table[class=body] p,\n"
                + "        table[class=body] ul,\n"
                + "        table[class=body] ol,\n"
                + "        table[class=body] td,\n"
                + "        table[class=body] span,\n"
                + "        table[class=body] a {\n"
                + "          font-size: 16px !important; \n"
                + "        }\n"
                + "        table[class=body] .wrapper,\n"
                + "        table[class=body] .article {\n"
                + "          padding: 10px !important; \n"
                + "        }\n"
                + "        table[class=body] .content {\n"
                + "          padding: 0 !important; \n"
                + "        }\n"
                + "        table[class=body] .container {\n"
                + "          padding: 0 !important;\n"
                + "          width: 100% !important; \n"
                + "        }\n"
                + "        table[class=body] .main {\n"
                + "          border-left-width: 0 !important;\n"
                + "          border-radius: 0 !important;\n"
                + "          border-right-width: 0 !important; \n"
                + "        }\n"
                + "        table[class=body] .btn table {\n"
                + "          width: 100% !important; \n"
                + "        }\n"
                + "        table[class=body] .btn a {\n"
                + "          width: 100% !important; \n"
                + "        }\n"
                + "        table[class=body] .img-responsive {\n"
                + "          height: auto !important;\n"
                + "          max-width: 100% !important;\n"
                + "          width: auto !important; \n"
                + "        }\n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          PRESERVE THESE STYLES IN THE HEAD\n"
                + "      ------------------------------------- */\n"
                + "      @media all {\n"
                + "        .ExternalClass {\n"
                + "          width: 100%; \n"
                + "        }\n"
                + "        .ExternalClass,\n"
                + "        .ExternalClass p,\n"
                + "        .ExternalClass span,\n"
                + "        .ExternalClass font,\n"
                + "        .ExternalClass td,\n"
                + "        .ExternalClass div {\n"
                + "          line-height: 100%; \n"
                + "        }\n"
                + "        .apple-link a {\n"
                + "          color: inherit !important;\n"
                + "          font-family: inherit !important;\n"
                + "          font-size: inherit !important;\n"
                + "          font-weight: inherit !important;\n"
                + "          line-height: inherit !important;\n"
                + "          text-decoration: none !important; \n"
                + "        }\n"
                + "        #MessageViewBody a {\n"
                + "          color: inherit;\n"
                + "          text-decoration: none;\n"
                + "          font-size: inherit;\n"
                + "          font-family: inherit;\n"
                + "          font-weight: inherit;\n"
                + "          line-height: inherit;\n"
                + "        }\n"
                + "        .btn-primary table td:hover {\n"
                + "          background-color: #34495e !important; \n"
                + "        }\n"
                + "        .btn-primary a:hover {\n"
                + "          background-color: #34495e !important;\n"
                + "          border-color: #34495e !important; \n"
                + "        } \n"
                + "      }\n"
                + "\n"
                + "    </style>\n"
                + "  </head>\n"
                + "  <body class=\"\">\n"
                + "    <span class=\"preheader\"></span>\n"
                + "    <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"body\">\n"
                + "      <tr>\n"
                + "        <td>&nbsp;</td>\n"
                + "        <td class=\"container\">\n"
                + "          <div class=\"content\">\n"
                + "\n"
                + "            <!-- START CENTERED WHITE CONTAINER -->\n"
                + "            <table role=\"presentation\" class=\"main\">\n"
                + "\n"
                + "              <!-- START MAIN CONTENT AREA -->\n"
                + "              <tr>\n"
                + "                <td class=\"wrapper\">\n"
                + "                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                    <tr>\n"
                + "                      <td>\n"
                + "                        <p>Dear <b>" + name + "</b>,</p>\n"
                + "                        <p>We regret to inform you that your booked tour [<b>"+tourName+"</b> at <b>"+registrationDate+"</b>] was canceled because of some reasons.</p>\n"
                + "                        <p>We apologise for any inconvenience caused.</p>\n"
                + "                        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"btn btn-primary\">\n"
                + "                          <tbody>\n"
                + "                            <tr>\n"
                + "                              <td align=\"left\">\n"
                + "                                <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                                  <tbody>\n"
                + "                                    <tr>\n"
                + "                                      <td> <a href=\"#\" target=\"_blank\">Back to website</a> </td>\n"
                + "                                    </tr>\n"
                + "                                  </tbody>\n"
                + "                                </table>\n"
                + "                              </td>\n"
                + "                            </tr>\n"
                + "                          </tbody>\n"
                + "                        </table>\n"
                + "                        <p>We wish you a good day.</p>\n"
                + "                        <p>Thank for visiting our website.</p>\n"
                + "                      </td>\n"
                + "                    </tr>\n"
                + "                  </table>\n"
                + "                </td>\n"
                + "              </tr>\n"
                + "\n"
                + "            <!-- END MAIN CONTENT AREA -->\n"
                + "            </table>\n"
                + "            <!-- END CENTERED WHITE CONTAINER -->\n"
                + "\n"
                + "            <!-- START FOOTER -->\n"
                + "            <div class=\"footer\">\n"
                + "              <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                <tr>\n"
                + "                  <td class=\"content-block\">\n"
                + "                    <span class=\"apple-link\"></span>\n"
                + "                    \n"
                + "                  </td>\n"
                + "                </tr>\n"
                + "                <tr>\n"
                + "                  <td class=\"content-block powered-by\">\n"
                + "                    East 2 West Tours and Travels.\n"
                + "                  </td>\n"
                + "                </tr>\n"
                + "              </table>\n"
                + "            </div>\n"
                + "            <!-- END FOOTER -->\n"
                + "\n"
                + "          </div>\n"
                + "        </td>\n"
                + "        <td>&nbsp;</td>\n"
                + "      </tr>\n"
                + "    </table>\n"
                + "  </body>\n"
                + "</html>";
    }
}
